"""New

Revision ID: 5284ee2ff6e5
Revises: e420dcadc530
Create Date: 2024-04-14 22:27:48.956475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5284ee2ff6e5'
down_revision: Union[str, None] = 'e420dcadc530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('room_id', sa.Integer(), nullable=True))
    op.add_column('booking', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('booking', sa.Column('date_from', sa.Date(), nullable=False))
    op.add_column('booking', sa.Column('date_to', sa.Date(), nullable=False))
    op.add_column('booking', sa.Column('total_cost', sa.Integer(), sa.Computed('(date_from - date_to) * price', ), nullable=True))
    op.add_column('booking', sa.Column('total_days', sa.Integer(), sa.Computed('date_from - date_to', ), nullable=True))
    op.create_foreign_key(None, 'booking', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'booking', 'room', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_column('booking', 'total_days')
    op.drop_column('booking', 'total_cost')
    op.drop_column('booking', 'date_to')
    op.drop_column('booking', 'date_from')
    op.drop_column('booking', 'user_id')
    op.drop_column('booking', 'room_id')
    # ### end Alembic commands ###
